### ISSUE TITLE
Return Exception On Error API Response

### ISSUE THREAD

**Issue by SankyuTech** [SankyuTech/stinvoice-adapter#1]
https://github.com/SankyuTech/stinvoice-adapter/blob/ad0e7344fba4a43087c5f8385abaaad87fde467e/src/One/Submission.php

- New function added, provide user check their credential valid or not.
function name : checkAccess()
- The error message response by API is correct, however package return as exception.

- New function added, provide user to validate their tax no
function name : checkIdentificationParty()

@tajulasri

**Comment by tajulasri** [comment]
@warfee check branch develop for this issue, https://github.com/SankyuTech/stinvoice-adapter/commit/e249539f4dc83783b6eb23d051a291c8d883cffa. Kindly use try and catch for implementation purpose.

**Comment by SankyuTech** [comment]
Try catch implemented handle for 401 and 500 error code. 
Return api return instead.
